[cerebrium.deployment]
name = "exobengal-api"
python_version = "3.10"
docker_base_image_url = "python:3.10-bookworm"
disable_auth = true
include = ['./exobengal-api/*', './models/*', './main.py', './requirements.txt']
exclude = ['.*', '__pycache__', '*.pyc', '.git']

[cerebrium.hardware]
cpu = 2.0
memory = 4.0
compute = "CPU"
provider = "aws"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 3
cooldown = 10
replica_concurrency = 1
scaling_metric = "concurrency_utilization"

[cerebrium.predict]
entrypoint = "main.py"
function = "predict"

[cerebrium.health]
entrypoint = "main.py"
function = "health_check"

[cerebrium.functions.get_model_info]
entrypoint = "main.py"
function = "get_model_info"

[cerebrium.functions.init]
entrypoint = "main.py"
function = "init"

